// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvMCfJ70wFv82QgXmaXLXhI2rYluy0or4',
    appId: '1:720354675012:web:5038e5cdb6a1847f33af11',
    messagingSenderId: '720354675012',
    projectId: 'employee-e9564',
    authDomain: 'employee-e9564.firebaseapp.com',
    storageBucket: 'employee-e9564.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBED6zMTbi5p7o0i2YTxOdEAUeS4473DWE',
    appId: '1:720354675012:android:ba1c6bd08637f79f33af11',
    messagingSenderId: '720354675012',
    projectId: 'employee-e9564',
    storageBucket: 'employee-e9564.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE7HwG-EiqW-vCZYDFA8HGjhTKmfP4ZUE',
    appId: '1:720354675012:ios:07b8dc1b884bd33f33af11',
    messagingSenderId: '720354675012',
    projectId: 'employee-e9564',
    storageBucket: 'employee-e9564.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE7HwG-EiqW-vCZYDFA8HGjhTKmfP4ZUE',
    appId: '1:720354675012:ios:07b8dc1b884bd33f33af11',
    messagingSenderId: '720354675012',
    projectId: 'employee-e9564',
    storageBucket: 'employee-e9564.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvMCfJ70wFv82QgXmaXLXhI2rYluy0or4',
    appId: '1:720354675012:web:12d4da634e33c86333af11',
    messagingSenderId: '720354675012',
    projectId: 'employee-e9564',
    authDomain: 'employee-e9564.firebaseapp.com',
    storageBucket: 'employee-e9564.firebasestorage.app',
  );
}
